[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
  let g:vim_markdown_json_frontmatter = 1
  let g:vim_markdown_new_list_item_indent = 0
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'qnighy/satysfi.vim'
on_ft = ['satysfi']

